# 2022.12.17 복습 정리

## 예외와 클래스
컴퓨터 하드웨어의 고장으로 인해 응용 프로그램 실행 오류가 발생하는 것을 자바에서는 에러라고 한다.

자바에서 예외란 잘못된 사용 또는 코딩으로 인한 오류를 의미한다.

-   예외가 발생되면 프로그램은 곧바로 종료된다는 점에서는 에러와 동일하지만, 예외 처리를 통해 계속 실행 상태를 유지할 수 있다.
    - 일반예외(Exception) : 컴파일러가 예외 처리 코드 여부를 검사하는 예외
    - 실행 예외(Runtime Exception) : 컴파일러가 예외 처리 코드 여부를 검사하지 않는 예외
    - Compile Exception : 컴파일 시점에 발생하는 예외, 이클립스가 빨간 줄로 표시해주는 예외
    - Checked Exception : 코드로 예외발생을 차단할 수 없기 때문에 예외처리를 강제하는 Exception
      - Exception 클래스를 상속받은 클래스를 만들면 Checked Exception으로 사용 가능
    - Unchecked Exception : 코드로 예외발생을 차단할 수 있기 때문에 예외처리를 강제하지 않는 Exception
        - Runtime Exception을 상속받은 클래스를 만들면 Unchecked Exception 사용 가능
- 자바는 예외가 발생하면 에외 클래스로부터 객체를 생성한다.
- 자바의 모든 에러와 예외 클래스는 Throwable을 상속받아 만들어지고 추가적으로 예외 클래스는 java.lang.Exception 클래스를 상속받는다.

## 예외 처리 코드 
예외 처리  코드란, 예외가 발생했을 때 프로그램의 갑작스런 종료를 막고 정상 실행을 유지할 수 있도록 처리하는 코드를 의미한다.

ex) try - catch - finally 블록(예외가 발생했을 경우)
```Java
try{

    //예외 발생 가능한 코드(예외 발생시)


}
catch(예외클래스 e){
    
    //예외처리

}
finally{

    //항상실행

}

```

try 블록에서 작성한 코드가 예외 없이 정상 실행되면 catch 블록은 실행하지 않고 finally 블록이 실행된다. 그러나 try 블록에서 예외가 발생하면 catch 블록이 실행되고 연이어 finally 블록이 실행된다. 

예외 발생 여부와 상관없이 finally 블록은 항상 실행된다.(try, catch 블록에서 return문을 사용하더라도 finally 블록은 항상 실행)(생략 가능)


## 예외 종류에 따른 처리 
catch 블록의 예외 클래스는 try 블록에서 발생된 예외의 종류를 의미, 해당 타입의 예외가 발생하면 catch 블록이 선택되어 실행된다.
- catch 블록이 여러 개라 할지라도 catch 블록은 단 하나만 실행된다. 그 이유는 try 블록에서 동시 다발적으로 예외가 발생하지 않으며 하나의 예외가 발생하면 즉시 실행을 멈추고 해당 catch 블록으로 이동하기 때문이다.
- 처리해야 할 예외 클래스들이 상속 관계에 있을 떄는 **하위 클래스** catch 블록을 먼저 작성하고 상위 클래스 catch 블록을 나중에 작성해야 한다. 예외가 발생하면 catch 블록은 위에서부터 차례대로 검사 대상이 되는데 하위 예외도 상위 클래스 타입이므로 상위 클래스 catch 블록이 먼저 검사 대상이 되면 안된다.
- 두 개 이상의 예외를 하나의 catch 블록으로 동일하게 예외 처리하고 싶을 때는 catch 블록에 예외 클래스를 기호 |로 연결하면 된다.

## 리소스 자동 닫기 
리소스(resource)란 데이터를 제공하는 객체를 의미, 리소스 사용하기 위해 열어야(open) 하며, 사용이 끝난 다음엔 닫아야(close)gksek.

ex) try - with - resources 블록
예외 발갱 여부와 상관없이 리소스를 자동으로 닫아준다. try 괄호 안에 리소스를 여는 코드를 작성하면 try 블록이 정상적으로 실행을 완료했거나 도중에 예외가 발생하면 자동으로 리소스의 close() 메소드가 호출된다.

```Java
try(FileInputStream fis = new FileInputStream("file.txt"){

 //예외 발생 가능한 코드


}
catch(IOException e){
    
    //예외처리

}

```

- 해당 블록을 사용하기 위해서는 리소스는 java.lang.AutoCloseable 인터페이스를 구현해서 AutoCloseable 인터페이스의 close() 매소드를 재정의해야 한다.

```Java
public class FileInputStream implements AutoCloseable{

    @Override
    public void close() throws Exception{ ... }
}

```
복수 개의 리소스를 사용해야 한다면 try( ) 괄호 안에 세미콜론(;)으로 구분해서 리소스를 여는 코드를 작성하면 된다.


## 예외 떠넘기기
메소드 내부에서 예외가 발생할 때 메소드를 호출한 곳으로 예외를 떠넘길 수도 있다. 이때 사용하는 키워드가 throws이다. throws는 메소드 선언부 끝에 작성하는데 떠넘길 예외 클래스를 쉽표로 구분해서 나열해주면 된다.

```Java
리턴타입 메소드명(매개변수, ... ) throws 예외클래스1, 예외클래스2, ...{

}

```

throws 키워드가 붙어 있는 메소드에서 해당 예외를 처리하지 않고 떠넘겼기 때문에 이 메소드를 호출하는 곳에서 예외를 받아 처리해야 한다.

나열해야 할 예외 클래스가 많을 경우에는 throws Exception 또는 throws Throwable만으로 모든 예외를 떠넘길 수도 있다.

```Java
리턴타입 메소드명(매개변수, ...) throws Exception{

}

```

main 메소드에서도 throws 키워드를 사용해서 예외를 떠넘길 수 있는데 결국 JVM이 최종적으로 예외 처리를 하게 된다. JVM은 예외의 내용을 콘솔에 출력하는 것으로 예외 처리를 한다.

```Java
public static void main(String[] args) throws Exception{

}

```

## 사용자 정의 예외
컴파일러가 체크하는 일반 예외로 선언할 수도 있고 컴파일러가 체크하지 않는 실행 예외로 선언할 수도 있다. 통상적으로 일반 예외는 Exception의 자식 클래스로 선언하고 실행 예외는 RuntimeException의 자식 클래스로 선언한다.

```Java
public static XXException extends (Exception | RuntimeException){ 
    public XXXException(){

        //기본 생성자

    }

    public XXXException(String message){ // 예외 메세지를 입력받는 생성자 
        super(message);
    }

}

```

사용자 정의 예외 클래스에는 기본 생성자와 예외 메시지를 입력받는 생성자를 선언해준다. 예외 메세지는 부모 생성자 매개값으로 넘겨주는데, 그 이유는 예외 객체의 공통 메소드인 getMessage()의 리턴값으로 사용하기 위해서이다.





